#!/bin/sh -e

case "$1" in
     remove|purge)
	[ -d /usr/share/deepin-software-center ] && rm /usr/share/deepin-software-center -r
	;;
     update|upgrade)
	echo "$1 will keep deepin software center generate data"
	;;
esac

exit 0
